// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgHzDSsCatg1ECgQYoQAPITKSu_aTkoDQ',
    appId: '1:366868075744:web:f9705d60b13bd4785f2c85',
    messagingSenderId: '366868075744',
    projectId: 'fluttercrud-db7e8',
    authDomain: 'fluttercrud-db7e8.firebaseapp.com',
    storageBucket: 'fluttercrud-db7e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaJJXfTFdFsWFINOxQnWoQZriyZafsUCI',
    appId: '1:366868075744:android:41d8d91ba366edb65f2c85',
    messagingSenderId: '366868075744',
    projectId: 'fluttercrud-db7e8',
    storageBucket: 'fluttercrud-db7e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuzhM5abfATTrsqSchBub-_BLVF36vOZQ',
    appId: '1:366868075744:ios:9a3def0f93bccef45f2c85',
    messagingSenderId: '366868075744',
    projectId: 'fluttercrud-db7e8',
    storageBucket: 'fluttercrud-db7e8.appspot.com',
    iosClientId: '366868075744-3682ovelm6c19cjr0bi8pbi6mvu7r2ri.apps.googleusercontent.com',
    iosBundleId: 'epn.edu.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuzhM5abfATTrsqSchBub-_BLVF36vOZQ',
    appId: '1:366868075744:ios:9a3def0f93bccef45f2c85',
    messagingSenderId: '366868075744',
    projectId: 'fluttercrud-db7e8',
    storageBucket: 'fluttercrud-db7e8.appspot.com',
    iosClientId: '366868075744-3682ovelm6c19cjr0bi8pbi6mvu7r2ri.apps.googleusercontent.com',
    iosBundleId: 'epn.edu.crud',
  );
}
